import { readFile, rm } from 'node:fs/promises';
import path from 'node:path';
import {
  applyLeaf,
  atomicWrite,
  backupPath,
  inspectLeaf,
  JstackError,
  leafState,
  loadSource,
  loadState,
  pathExists,
  relativeStatePath,
  sha256,
  sourceRevision,
  staleEntryStatus,
  targetsFor,
} from './core.mjs';
import {
  configEntry,
  ensureParent,
  inspectCodexMcp,
  inspectJsoncEntries,
  inspectJsonMcp,
  mergeJsonMcp,
  opencodeMcpCompatible,
  opencodeServers,
  updateCodexMcp,
  updateJsoncEntries,
} from './config.mjs';

function renderPiAgent(agent) {
  return [
    '---',
    '# Generated by jstack. Edit the canonical subagent source instead.',
    `name: ${agent.id}`,
    `description: ${JSON.stringify(agent.description)}`,
    'inheritProjectContext: true',
    'inheritSkills: true',
    '---',
    '',
    agent.body.replace(/\s+$/, ''),
    '',
  ].join('\n');
}

function renderCodexAgent(agent) {
  return [
    '# Generated by jstack. Edit the canonical subagent source instead.',
    `name = ${JSON.stringify(agent.id)}`,
    `description = ${JSON.stringify(agent.description)}`,
    `developer_instructions = ${JSON.stringify(agent.body.replace(/\s+$/, ''))}`,
    '',
  ].join('\n');
}

function renderPrimeSubagentSkill(source) {
  const promptRoot = '../../prompts';
  const roles = source.subagents.map(
    (agent) => `| \`${agent.id}\` | ${agent.description.replace(/\s+/g, ' ').trim()} | \`${promptRoot}/${agent.id}.md\` |`,
  );
  return [
    '---',
    'name: jstack-subagents',
    'description: Prime Agent only. Adapt JStack explorer, planner, worker, reviewer, oracle, and thermo role contracts to RLM children when a JStack workflow delegates work inside Prime Agent.',
    'compatibility: Prime Agent with RLM and agent-message skills.',
    '---',
    '',
    '# JStack Subagents for Prime Agent',
    '',
    "> Runtime guard: use this adapter only inside Prime Agent. On Codex, Cursor, Pi, or OpenCode, do not call `rlm()` or `agent_message`; use that host's named-role adapter from `../../references/host-conventions.md`.",
    '',
    'JStack role IDs are prompt contracts, not Prime-native named agent types. Read the selected installed prompt, include its contract in a self-contained child task, and use Prime RLM directly.',
    '',
    '## Installed roles',
    '',
    '| Role | Purpose | Prompt |',
    '|---|---|---|',
    ...roles,
    '',
    '## Spawn contract',
    '',
    '1. Read the selected role prompt. Compose a task containing that role contract, the concrete goal, relevant paths and context, constraints, definition of done, and the explicit reply instruction below.',
    '2. Require the child to send its terminal handoff with:',
    '',
    '   ```python',
    '   await agent_message.send(message, receiver_role="parent")',
    '   ```',
    '',
    '3. Admit the child with a stable unique name:',
    '',
    '   ```python',
    '   handle = await rlm(prompt, name="role-task")',
    '   ```',
    '',
    '   The return value contains only `rlm_child_id`, `name`, `session_dir`, and `model`. It confirms admission immediately and never contains the child answer.',
    '4. Admit independent children in separate calls, retaining every handle. After admitting the wave, end the parent turn instead of polling or awaiting completion. Replies arrive as ordinary messages and may span multiple parent turns.',
    '5. Do not review, integrate, or synthesize until every admitted child has sent an explicit terminal handoff. A spawn return value is not a handoff.',
    '6. Recover handles with `await rlm.list_subagents()`. Send a follow-up only to a retained direct child with `await agent_message.send(message, receiver_role="child", receiver_name=handle.name)`.',
    '',
    'Nested children report to their direct parent. That parent must aggregate and relay the handoff upward. Keep one writer per overlapping filesystem scope.',
    '',
    '## Models and thinking',
    '',
    '- A child inherits the parent model and thinking configuration by default.',
    '- For an explicit model override, call `await rlm.find_models(...)` and pass an exact returned `provider/model` selector as `model=`. Do not hard-code an unavailable provider slug.',
    '- `rlm()` supports only `name` and `model` options. Do not pass an invented per-child thinking option.',
    '- GPT-5.6 models support the `max` thinking level. Honor an explicit `max` request on the parent/session; do not clamp it to `xhigh`.',
    '- Always honor explicit user model overrides.',
    '',
  ].join('\n');
}

function buildLeaves({ sourceRoot, source, hosts, targets, global }) {
  const leaves = [];
  for (const skill of source.skills) {
    leaves.push({
      kind: 'symlink',
      path: path.join(targets.agentsRoot, 'skills', skill.id),
      target: path.dirname(skill.filePath),
      relative: !global,
      label: `skill ${skill.id}`,
    });
  }
  leaves.push({
    kind: 'symlink',
    path: path.join(targets.agentsRoot, 'references'),
    target: path.join(sourceRoot, 'references'),
    relative: !global,
    label: 'shared references',
  });
  leaves.push({
    kind: 'symlink',
    path: path.join(targets.agentsRoot, '.mcp.json'),
    target: source.mcpPath,
    relative: !global,
    label: 'portable MCP source',
  });
  for (const agent of source.subagents) {
    leaves.push({
      kind: 'file',
      path: path.join(targets.agentsRoot, 'prompts', `${agent.id}.md`),
      content: `${agent.body.replace(/\s+$/, '')}\n`,
      label: `prompt ${agent.id}`,
    });
    if (hosts.has('pi')) {
      leaves.push({
        kind: 'file',
        path: path.join(targets.agentsRoot, 'agents', `${agent.id}.md`),
        content: renderPiAgent(agent),
        label: `Pi agent ${agent.id}`,
      });
    }
    if (hosts.has('cursor')) {
      leaves.push({
        kind: 'symlink',
        path: path.join(targets.cursorRoot, 'agents', `${agent.id}.md`),
        target: agent.filePath,
        relative: !global,
        label: `Cursor agent ${agent.id}`,
      });
    }
    if (hosts.has('codex')) {
      leaves.push({
        kind: 'file',
        path: path.join(targets.codexRoot, 'agents', `${agent.id}.toml`),
        content: renderCodexAgent(agent),
        label: `Codex agent ${agent.id}`,
      });
    }
  }
  if (hosts.has('prime')) {
    leaves.push({
      kind: 'file',
      path: path.join(targets.agentsRoot, 'skills', 'jstack-subagents', 'SKILL.md'),
      content: renderPrimeSubagentSkill(source),
      label: 'Prime subagent adapter',
    });
  }
  return leaves;
}

function stateKey(targets, filePath) {
  return `path:${relativeStatePath(targets.root, filePath)}`;
}

function configKey(host, section, id) {
  return `config:${host}:${section}:${id}`;
}

function ownedConfigKeys(state, host, section) {
  const prefix = `config:${host}:${section}:`;
  return new Set(Object.keys(state.entries).filter((key) => key.startsWith(prefix)).map((key) => key.slice(prefix.length)));
}

function opencodeAgents(source, global) {
  return Object.fromEntries(
    source.subagents.map((agent) => [
      agent.id,
      {
        description: agent.description,
        mode: 'subagent',
        prompt: global
          ? `{file:~/.agents/prompts/${agent.id}.md}`
          : `{file:./.agents/prompts/${agent.id}.md}`,
      },
    ]),
  );
}

async function readTextOr(filePath, fallback) {
  return (await pathExists(filePath)) ? readFile(filePath, 'utf8') : fallback;
}

async function preflightLeaves(leaves, state, targets, force) {
  const results = new Map();
  const conflicts = [];
  for (const item of leaves) {
    const key = stateKey(targets, item.path);
    const result = await inspectLeaf(item, state.entries[key]);
    results.set(item.path, result);
    if (result.status === 'conflict' && !force) conflicts.push(`${item.label}: ${item.path}`);
  }

  const desiredKeys = new Set(leaves.map((item) => stateKey(targets, item.path)));
  const stale = [];
  for (const [key, entry] of Object.entries(state.entries)) {
    if (!key.startsWith('path:') || desiredKeys.has(key)) continue;
    const storedPath = key.slice('path:'.length);
    const filePath = path.isAbsolute(storedPath) ? storedPath : path.join(targets.root, storedPath);
    const status = await staleEntryStatus(filePath, entry);
    stale.push({ key, filePath, status });
    if (status === 'modified' && !force) conflicts.push(`modified stale installer entry: ${filePath}`);
  }
  if (conflicts.length > 0) {
    throw new JstackError(`Installation conflicts:\n- ${conflicts.join('\n- ')}\nUse --force to back them up and continue.`, 1);
  }
  return { results, stale };
}

async function preflightOpenCode({ source, targets, state, force, withMcp, global }) {
  const text = await readTextOr(targets.opencodeConfig, '{}\n');
  const agents = opencodeAgents(source, global);
  const agentOwned = ownedConfigKeys(state, 'opencode', 'agent');
  const agentStatus = inspectJsoncEntries(text, 'agent', agents, agentOwned);
  for (const id of Object.keys(agents)) {
    if (agentStatus[id].status === 'ok' && !agentOwned.has(id)) {
      agentStatus[id] = { status: 'conflict' };
    }
  }
  const mcp = withMcp ? opencodeServers(source.mcp.mcpServers) : {};
  const mcpOwned = ownedConfigKeys(state, 'opencode', 'mcp');
  const mcpStatus = withMcp
    ? inspectJsoncEntries(text, 'mcp', mcp, mcpOwned, opencodeMcpCompatible)
    : {};
  const conflicts = [
    ...Object.entries(agentStatus).filter(([, result]) => result.status === 'conflict').map(([id]) => `OpenCode agent.${id}`),
    ...Object.entries(mcpStatus).filter(([, result]) => result.status === 'conflict').map(([id]) => `OpenCode mcp.${id}`),
  ];
  if (conflicts.length > 0 && !force) {
    throw new JstackError(`Installation conflicts:\n- ${conflicts.join('\n- ')}\nUse --force to back up opencode.json.`, 1);
  }
  return { text, agents, agentOwned, agentStatus, mcp, mcpOwned, mcpStatus, hasForcedConflict: conflicts.length > 0 };
}

async function applyOpenCode({ plan, targets, force }) {
  let text = updateJsoncEntries(plan.text, 'agent', plan.agents, plan.agentOwned, force);
  if (Object.keys(plan.mcp).length > 0) {
    text = updateJsoncEntries(text, 'mcp', plan.mcp, plan.mcpOwned, force, opencodeMcpCompatible);
  }
  await ensureParent(targets.opencodeConfig);
  await atomicWrite(targets.opencodeConfig, text.endsWith('\n') ? text : `${text}\n`);
}

async function installMcp({ source, hosts, targets, state, force, backupOnce }) {
  const nextEntries = {};
  const sourceServers = source.mcp.mcpServers;
  const jsonHosts = [];
  if (hosts.has('pi')) jsonHosts.push(['pi', targets.piMcp]);
  if (hosts.has('cursor')) jsonHosts.push(['cursor', targets.cursorMcp]);
  for (const [host, filePath] of jsonHosts) {
    const statuses = await inspectJsonMcp(filePath, sourceServers);
    const conflicts = Object.entries(statuses).filter(([, status]) => status === 'conflict');
    const owned = ownedConfigKeys(state, host, 'mcp');
    const unownedConflicts = conflicts.filter(([id]) => !owned.has(id));
    if (unownedConflicts.length > 0 && !force) {
      throw new JstackError(`MCP conflicts in ${filePath}: ${unownedConflicts.map(([id]) => id).join(', ')}`, 1);
    }
    if (unownedConflicts.length > 0) await backupOnce(filePath);
    await mergeJsonMcp(filePath, sourceServers, owned, force);
    for (const [id, desired] of Object.entries(sourceServers)) {
      if (statuses[id] !== 'ok' || owned.has(id)) nextEntries[configKey(host, 'mcp', id)] = configEntry('mcp', filePath, desired);
    }
  }

  if (hosts.has('codex')) {
    const text = await readTextOr(targets.codexConfig, '');
    const statuses = inspectCodexMcp(text, sourceServers);
    if (Object.values(statuses).includes('conflict')) {
      if (!force) throw new JstackError(`MCP conflicts in ${targets.codexConfig}.`, 1);
      await backupOnce(targets.codexConfig);
    }
    await ensureParent(targets.codexConfig);
    await atomicWrite(targets.codexConfig, updateCodexMcp(text, sourceServers, force));
    for (const [id, desired] of Object.entries(sourceServers)) {
      nextEntries[configKey('codex', 'mcp', id)] = configEntry('mcp', targets.codexConfig, desired);
    }
  }
  return nextEntries;
}

async function preflightMcp({ source, hosts, targets, state, force }) {
  const sourceServers = source.mcp.mcpServers;
  const jsonHosts = [];
  if (hosts.has('pi')) jsonHosts.push(['pi', targets.piMcp]);
  if (hosts.has('cursor')) jsonHosts.push(['cursor', targets.cursorMcp]);
  for (const [host, filePath] of jsonHosts) {
    const statuses = await inspectJsonMcp(filePath, sourceServers);
    const owned = ownedConfigKeys(state, host, 'mcp');
    const conflicts = Object.entries(statuses).filter(([id, status]) => status === 'conflict' && !owned.has(id));
    if (conflicts.length > 0 && !force) {
      throw new JstackError(`MCP conflicts in ${filePath}: ${conflicts.map(([id]) => id).join(', ')}`, 1);
    }
  }
  if (hosts.has('codex')) {
    const statuses = inspectCodexMcp(await readTextOr(targets.codexConfig, ''), sourceServers);
    if (Object.values(statuses).includes('conflict') && !force) {
      throw new JstackError(`MCP conflicts in ${targets.codexConfig}.`, 1);
    }
  }
}

export async function install(options) {
  const source = await loadSource(options.sourceRoot);
  const targets = targetsFor(options);
  const { statePath, state } = await loadState(targets);
  const leaves = buildLeaves({ sourceRoot: options.sourceRoot, source, hosts: options.hosts, targets, global: options.global });
  const leafPlan = await preflightLeaves(leaves, state, targets, options.force);
  const openCodePlan = options.hosts.has('opencode')
    ? await preflightOpenCode({
        source,
        targets,
        state,
        force: options.force,
        withMcp: options.withMcp,
        global: options.global,
      })
    : null;
  if (options.withMcp) {
    await preflightMcp({ source, hosts: options.hosts, targets, state, force: options.force });
  }
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const backedUp = new Set();
  const backupOnce = async (filePath) => {
    if (!(await pathExists(filePath)) || backedUp.has(filePath)) return;
    await backupPath(filePath, targets, timestamp);
    backedUp.add(filePath);
  };

  for (const stale of leafPlan.stale) {
    if (stale.status === 'missing') continue;
    if (stale.status === 'modified') await backupOnce(stale.filePath);
    else await rm(stale.filePath, { recursive: true, force: true });
  }
  for (const item of leaves) {
    const result = leafPlan.results.get(item.path);
    if (result.status === 'conflict') await backupOnce(item.path);
    if (result.status !== 'ok') await applyLeaf(item);
  }
  if (openCodePlan) {
    if (openCodePlan.hasForcedConflict) await backupOnce(targets.opencodeConfig);
    await applyOpenCode({ plan: openCodePlan, targets, force: options.force });
  }

  let configEntries = {};
  if (options.withMcp) {
    configEntries = await installMcp({ source, hosts: options.hosts, targets, state, force: options.force, backupOnce });
  }

  const entries = Object.fromEntries(
    Object.entries(state.entries).filter(([key]) => key.includes(':mcp:') && !options.withMcp),
  );
  for (const item of leaves) entries[stateKey(targets, item.path)] = await leafState(item, targets);
  if (openCodePlan) {
    for (const [id, value] of Object.entries(openCodePlan.agents)) {
      if (openCodePlan.agentOwned.has(id) || openCodePlan.agentStatus[id].status !== 'ok') {
        entries[configKey('opencode', 'agent', id)] = configEntry('agent', targets.opencodeConfig, value);
      }
    }
    for (const [id, value] of Object.entries(openCodePlan.mcp)) {
      if (openCodePlan.mcpOwned.has(id) || openCodePlan.mcpStatus[id].status !== 'ok') {
        entries[configKey('opencode', 'mcp', id)] = configEntry('mcp', targets.opencodeConfig, value);
      }
    }
  }
  Object.assign(entries, configEntries);
  const revision = sourceRevision(options.sourceRoot);
  const nextState = {
    version: 1,
    sourceRoot: options.sourceRoot,
    sourceRevision: revision.revision,
    sourceDirty: revision.dirty,
    hosts: [...options.hosts].sort(),
    withMcp: options.withMcp,
    entries,
  };
  await atomicWrite(statePath, `${JSON.stringify(nextState, null, 2)}\n`);
  return { targets, leafCount: leaves.length, revision, backups: backedUp.size };
}

function pushStatuses(lines, prefix, statuses, optional, problems) {
  for (const [id, value] of Object.entries(statuses)) {
    const status = typeof value === 'string' ? value : value.status;
    if (status === 'ok') lines.push(`[ok] ${prefix} ${id}`);
    else if (optional) lines.push(`[optional] ${prefix} ${id}: ${status}`);
    else {
      lines.push(`[drift] ${prefix} ${id}: ${status}`);
      problems.push(`${prefix} ${id}`);
    }
  }
}

export async function doctor(options) {
  const source = await loadSource(options.sourceRoot);
  const targets = targetsFor(options);
  const { state } = await loadState(targets);
  const leaves = buildLeaves({ sourceRoot: options.sourceRoot, source, hosts: options.hosts, targets, global: options.global });
  const lines = [];
  const problems = [];
  const revision = sourceRevision(options.sourceRoot);
  lines.push(`[source] ${revision.revision}${revision.dirty ? ' (dirty)' : ''}`);

  for (const item of leaves) {
    const result = await inspectLeaf(item, state.entries[stateKey(targets, item.path)]);
    if (result.status === 'ok') lines.push(`[ok] ${item.label}`);
    else {
      lines.push(`[drift] ${item.label}: ${result.status}`);
      problems.push(item.label);
    }
  }
  if (options.hosts.has('opencode')) {
    const plan = await preflightOpenCode({
      source,
      targets,
      state,
      force: true,
      withMcp: options.withMcp,
      global: options.global,
    });
    pushStatuses(lines, 'OpenCode agent', plan.agentStatus, false, problems);
    if (options.withMcp) pushStatuses(lines, 'OpenCode MCP', plan.mcpStatus, false, problems);
    else pushStatuses(lines, 'OpenCode MCP', inspectJsoncEntries(plan.text, 'mcp', opencodeServers(source.mcp.mcpServers), plan.mcpOwned, opencodeMcpCompatible), true, problems);
  }
  const optional = !options.withMcp;
  if (options.hosts.has('pi')) pushStatuses(lines, 'Pi MCP', await inspectJsonMcp(targets.piMcp, source.mcp.mcpServers), optional, problems);
  if (options.hosts.has('cursor')) pushStatuses(lines, 'Cursor MCP', await inspectJsonMcp(targets.cursorMcp, source.mcp.mcpServers), optional, problems);
  if (options.hosts.has('codex')) {
    const text = await readTextOr(targets.codexConfig, '');
    pushStatuses(lines, 'Codex MCP', inspectCodexMcp(text, source.mcp.mcpServers), optional, problems);
  }
  if (options.hosts.has('pi')) lines.push('[prerequisite] Pi requires the pi-subagents package; jstack does not install it.');
  return { healthy: problems.length === 0, lines, problems };
}
